# Generated by Django 3.2.7 on 2021-10-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_auto_20211005_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='theme2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='theme3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
