# Generated by Django 3.2.7 on 2021-10-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_auto_20211006_0949'),
    ]


