# Generated by Django 3.2.7 on 2021-10-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_auto_20211006_0951'),
    ]

