# Generated by Django 3.2.7 on 2021-10-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_remove_helloworld_text2'),
    ]

