# Generated by Django 3.2.7 on 2021-10-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_helloworld_text2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworld',
            name='text',
            field=models.CharField(max_length=255, default="", null=True),
        ),
    ]
