# Generated by Django 3.2.7 on 2021-10-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0010_auto_20211006_1011'),
    ]

