# Generated by Django 3.2.7 on 2021-10-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0011_remove_hello_text2'),
    ]