# Generated by Django 3.2.7 on 2021-10-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0013_auto_20211006_1131'),
    ]

    operations = [
    ]
