# Generated by Django 3.2.7 on 2021-10-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0014_auto_20211006_1224'),
    ]

    operations = [

    ]
