# Generated by Django 3.2.7 on 2021-10-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0015_alter_helloworld_text'),
    ]

    operations = [

    ]
