# Generated by Django 3.2.7 on 2021-10-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0016_auto_20211006_1427'),
    ]

    operations = [

    ]
