# Generated by Django 3.2.7 on 2021-10-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0018_auto_20211006_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworld',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
