# Generated by Django 3.2.7 on 2021-10-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0020_auto_20211026_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcond', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('downcond', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discond', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('transcond', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
