# Generated by Django 3.2.7 on 2021-10-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0021_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='field',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
