# Generated by Django 3.2.7 on 2021-10-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0022_condition_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='future',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
